### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by brawlawnzo** [brawlawnzo/gaussmixdetector#1]
# List of tasks and goals

- [ ] CRITICAL: There's practically no error handling.
- [ ] IMPORTANT: Should add a logger.
- [x] BUG: Should really look into the channel handling: https://github.com/brawlawnzo/gaussmixdetector/blob/ea9524a252f9fde0b0c24266f38d77073640722e/GaussMixDetector.cpp#L549
- [x] ISSUE: We should refer to frame itself, not its allocated copy every time.
- [x] MEMORY: Don't need double precision to store floating point matrices.
- [ ] ISSUE (algorithm): The first grabbed frame has too much influence on gaussians - adaptation algorithm needs testing.
- [ ] ISSUE (algorithm): Initial deviation can and should be calculated automatically (although will probably require max value range from user).
- [ ] ISSUE (algorithm): Gaussian destabilization should be solved by limiting the covariance matrices - question is how exactly.
- [x] PERFORMANCE: Computation-wise matrix inversion is the most costly - need to test various algorithms to find the most suited.
- [ ] PERFORMANCE: Should add the cv::isContinuous() functionality to per-pixel operations. (upd: Probably pointless -> test performance difference.)
- [ ] RESEARCH: Should test the algorithm on different color spaces, the most interesting being HSL and CIELAB.
- [ ] FEATURE: https://github.com/brawlawnzo/gaussmixdetector/blob/ea9524a252f9fde0b0c24266f38d77073640722e/GaussMixDetector.h#L12
